### ISSUE TITLE
Unhandled exception - Crash on Empty Shiny Report

### ISSUE THREAD

**Issue by kbtbc** [versx/WhMgr#13]
Bot started midnight routine, and crashed when the Shiny report was empty.  

Trace report:
11:59 PM [DEBUG] [BOT] MIDNIGHT 5/25/2020 11:59:59 PM
11:59 PM [DEBUG] [BOT] Starting automatic quest messages cleanup...
11:59 PM [DEBUG] [BOT] Posting shiny stats for guild MyGuild (#guildid#) in channel #ChannelID#
12:00 AM [DEBUG] [BOT] Unhandled exception caught.
12:00 AM [ERROR] [BOT] System.ArgumentException: Cannot send empty message
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WhMgr.Bot.<ResetQuests>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WhMgr.Bot.<<-ctor>b__7_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by kbtbc** [comment]
This issue also appears if I try the command `shiny-stats` in the bot channel.
In the console it errors (but does not cause a full crash like the midnight job): 
```
[2020-05-27 16:05:01 -04:00] [Brock] [Error] BigFun tried executing 'shiny-stats' but it errored: System.ArgumentException: Cannot send empty message
[Brock] BigFun tried executing 'shiny-stats' but it errored: System.ArgumentException: Cannot send empty message: BigFun tried executing 'shiny-stats' but it er
rored: System.ArgumentException: Cannot send empty message

```
In the Discord Bot channel, it returns this error:
![image](https://user-images.githubusercontent.com/7109934/83069359-bfd0d080-a037-11ea-8663-9528f2835dd0.png)

**Comment by versx** [comment]
I'll check if I can track down the issue, not sure why it's trying to send an empty message.

**Comment by versx** [comment]
This should be fixed in the `netcore` branch now.

**Comment by versx** [comment]
This should be fixed in latest, if it's not please reopen the issue.
