### ISSUE TITLE
v5 alarm casting from null to bool

### ISSUE THREAD

**Issue by clburlison** [versx/WhMgr#190]
This is with the v5 branch using a clean database (nothing migrated from v4 whmgr)

Will frequently have an alarm that triggers the following error.
```
info: WhMgr.Services.Alarms.AlarmControllerService[0]
      [Alamo Ranch] Found PokemonData [Alarm=MY-AMAZING-CITY, GuildId=XXXXXXXX]
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'WhMgr.Data.Contexts.MapDbContext'.
      System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.Boolean'.
         at MySqlConnector.Core.Row.GetBoolean(Int32 ordinal) in /_/src/MySqlConnector/Core/Row.cs:line 66
         at lambda_method718(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.Boolean'.
         at MySqlConnector.Core.Row.GetBoolean(Int32 ordinal) in /_/src/MySqlConnector/Core/Row.cs:line 66
         at lambda_method718(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
fail: WhMgr.Services.Alarms.AlarmControllerService[0]
      Error: System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.Boolean'.
         at MySqlConnector.Core.Row.GetBoolean(Int32 ordinal) in /_/src/MySqlConnector/Core/Row.cs:line 66
         at lambda_method718(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToDictionaryAsync[TSource,TKey,TElement](IQueryable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToDictionaryAsync[TSource,TKey,TElement](IQueryable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer, CancellationToken cancellationToken)
         at WhMgr.Services.Cache.MapDataCache.LoadMapData() in /home/whmgr/test/src/Services/Cache/MapDataCache.cs:line 163
         at WhMgr.Services.Cache.MapDataCache.GetPokestop(String id) in /home/whmgr/test/src/Services/Cache/MapDataCache.cs:line 49
         at WhMgr.Services.Webhook.Models.PokemonData.GetPropertiesAsync(AlarmMessageSettings properties) in /home/whmgr/test/src/Services/Webhook/Models/PokemonData.cs:line 508
         at WhMgr.Services.Webhook.Models.PokemonData.GenerateEmbedMessageAsync(AlarmMessageSettings settings) in /home/whmgr/test/src/Services/Webhook/Models/PokemonData.cs:line 416
         at WhMgr.Services.Alarms.AlarmControllerService.ProcessWorkItemAsync(AlarmTaskItem taskItem, CancellationToken stoppingToken) in /home/whmgr/test/src/Services/Alarms/AlarmControllerService.cs:line 717


```

**Comment by versx** [comment]
This should be fixed in latest push now.

**Comment by clburlison** [comment]
Confirmed this has fixed
